config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]

    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true
<<<<<<< HEAD

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end

=======
>>>>>>> message-device
end

app/models/concerns/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/concerns/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
<<<<<<< HEAD

  mount_uploader :image, ImageUploader
=======
>>>>>>> message-device
end

app/models/concerns/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,  :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id]
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/concerns/groups_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_with model: group, local: true do |f|
  - if group.errors.any?
    .SettingGroupForm__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, "グループ名", class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'グループ名を入力してください'
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      %label.SettingGroupForm__label チャットメンバーを追加
    .SettingGroupForm__rightField
      .UserSearch
        %input#UserSearch__field.SettingGroupForm__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #UserSearchResult
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, value: "チャットメンバー", class: "SettingGroupForm__label"
    .SettingGroupForm__rightField
      .ChatMembers
        .ChatMember
          %p.ChatMember__name= current_user.name
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
        - group.users.each do |user|
          - if current_user.name != user.name
            .ChatMember
              %p.ChatMember__name 
                = user.name
              .ChatMember__remove.ChatMember__button{"data-user-id": user.id, "data-user-name": user.name} 削除
              %input{name: "group[user_ids][]", type:"hidden", value: user.id}
  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField
      = f.submit class: 'SettingGroupForm__button'

app/views/groups/edit.html.haml
.SettingGroupForm
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
.SettingGroupForm
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tech
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_main_chat.html.haml
.mainChat
  .mainChat__groupInfo
    .text
      =@group.name
      .memberName
        -@group.users.each do |num|
          =num.name
    
    =link_to edit_group_path(@group),class: "edit" do 
      edit

  .mainChat__messageList
    = render @messages
    


  


  .mainChat__messageForm
    = form_with model: [@group, @message], html: {class: "mainChat__messageForm__text"}, local: true do |f|
      .input-box
        = f.text_field :content, class: 'input-box__text', placeholder: 'type a message'
        = f.label :image, class: 'input-box__image' do
          = icon('far', 'image', class: 'Form__icon')
          = f.file_field :image, class: 'input-box__file'
      = f.submit 'Send', class: 'submit-btn'

app/views/messages/_message.html.haml
.MessageBox{data: {message: {id: message.id}}}
  .groupChat
    .groupChatname
      = message.user.name
    .times
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
    
  .groupText
    - if message.content.present?
      %p.Message__content
        = message.content
    = image_tag message.image.url, class: 'Message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.sideBar
  .sideBar__user
    .sideBar__user--box
      .name
        = current_user.name
      .botton
        .botton_1
          = link_to new_group_path do
            = icon('fas', 'edit')
        .botton_2
          = link_to edit_user_path(current_user) do
            = icon('fas', 'cog')
  
  .sideBar__groupList
    - current_user.groups.each do |group|
      .sideBar__groupList__groupName
        = link_to group_messages_path(group) do
          .sideBar__groupList__groupMessage
            = group.name
          .sideBar__groupList__groupName
            = group.show_last_message

app/views/messages/index.html.haml
= javascript_include_tag 'autoReload'
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'